const $=s=>document.querySelector(s);const grid=$('#gameGrid'),modal=$('#gameModal'),mount=$('#gameMount'),titleEl=$('#gameTitle'),catEl=$('#gameCat'),descEl=$('#gameDesc'),highEl=$('#gameHigh'),hintEl=$('#controlHint');
let sound=true,activeCleanup=null,category='Alle';
const games=[
{id:'street',name:'Street Rush',cat:'Action',icon:'🏃',desc:'Dreispuriger Endless Runner mit Sprüngen, Rutschern und Hindernissen.',hint:'← → Spur wechseln · ↑ springen · ↓ ducken · Mobil: tippen/ziehen',start:streetRush},
{id:'blast',name:'Blast Maker',cat:'Puzzle',icon:'🧱',desc:'Setze Blöcke in ein Raster und räume komplette Reihen und Spalten ab.',hint:'Block wählen, drehen und ins Raster setzen.',start:blastMaker},
{id:'stack',name:'Stack Up',cat:'Casual',icon:'🏗️',desc:'Staple bewegte Plattformen möglichst hoch und verliere dabei nicht den Rhythmus.',hint:'Leertaste oder Tippen zum Ablegen.',start:stackUp},
{id:'snake',name:'Snake Arena',cat:'Arcade',icon:'🐍',desc:'Klassische Schlange mit wachsendem Feld, Bonusfrüchten und Highscore.',hint:'Pfeiltasten / WASD · Mobil über Wischgesten.',start:snakeArena},
{id:'flap',name:'Sky Flap',cat:'Arcade',icon:'🐦',desc:'Fliege durch Öffnungen, sammle Sterne und halte so lange wie möglich durch.',hint:'Leertaste / Klick / Tippen zum Flattern.',start:skyFlap},
{id:'brick',name:'Brick Breaker',cat:'Arcade',icon:'🔴',desc:'Zerlege farbige Ziegel mit Ball, Paddle und Bonus-Power-ups.',hint:'← → oder A/D · Maus/Touch bewegt das Paddle.',start:brickBreaker},
{id:'asteroid',name:'Astro Drift',cat:'Action',icon:'🚀',desc:'Drehe, beschleunige und schieße dich durch ein Feld aus Asteroiden.',hint:'← → drehen · ↑ Schub · Leertaste feuern.',start:astroDrift},
{id:'memory',name:'Memory Grid',cat:'Puzzle',icon:'🧠',desc:'Finde alle gleichen Paare mit möglichst wenigen Zügen.',hint:'Klicke zwei Karten an und merke dir ihre Position.',start:memoryGrid},
{id:'tiles',name:'Neon Tiles',cat:'Puzzle',icon:'🔢',desc:'Schiebe Zahlen zusammen und versuche das 2048-Ziel zu erreichen.',hint:'Pfeiltasten / WASD · Wischen auf Mobilgeräten.',start:neonTiles},
{id:'aim',name:'Aim Dash',cat:'Action',icon:'🎯',desc:'Treffe in 30 Sekunden so viele Ziele wie möglich – schnell und präzise.',hint:'Ziele anklicken/tippen.',start:aimDash},
{id:'goal',name:'Goal Rush',cat:'Sport',icon:'⚽',desc:'Schieße den Ball durch wechselnde Ziele und knacke deine Serie.',hint:'Ziehen/halten zum Zielen, loslassen zum Schuss.',start:goalRush},
{id:'fruit',name:'Fruit Slice',cat:'Arcade',icon:'🍉',desc:'Zerschneide aufsteigende Früchte per Maus oder Finger – Bomben zählen nicht.',hint:'Maus oder Finger ziehen und über Früchte schneiden.',start:fruitSlice},
{id:'dodge',name:'Laser Dodge',cat:'Action',icon:'⚡',desc:'Weiche Laserlinien aus und überlebe immer schneller werdende Wellen.',hint:'← → oder A/D bewegen · Mobil: links/rechts tippen.',start:laserDodge},
{id:'react',name:'Reaction Rush',cat:'Casual',icon:'🟢',desc:'Warte auf Grün und klicke so schnell wie möglich. Zu früh kostet Leben.',hint:'Klicken sobald das Feld grün wird.',start:reactionRush}
];
function escapeHtml(x){return x.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){const q=$('#search').value.trim().toLowerCase();const shown=games.filter(g=>(category==='Alle'||g.cat===category)&&(!q||g.name.toLowerCase().includes(q)||g.desc.toLowerCase().includes(q)));grid.innerHTML=shown.map(g=>`<article class="game-card" data-id="${g.id}"><div class="game-art">${g.icon}</div><span class="pill">${g.cat}</span><div class="game-info"><h3>${escapeHtml(g.name)}</h3><p>${escapeHtml(g.desc)}</p></div></article>`).join('');$('#countLabel').textContent=`${shown.length} Spiele`;grid.querySelectorAll('.game-card').forEach(c=>c.onclick=()=>openGame(c.dataset.id))}
function hsKey(id){return 'rg-hs-'+id}function getHS(id){return Number(localStorage.getItem(hsKey(id))||0)}function setHS(id,v){if(v>getHS(id)){localStorage.setItem(hsKey(id),String(v));return true}return false}
function openGame(id){const g=games.find(x=>x.id===id);if(!g)return; titleEl.textContent=g.name;catEl.textContent=g.cat.toUpperCase();descEl.textContent=g.desc;highEl.textContent=`Highscore: ${getHS(id)}`;hintEl.textContent=g.hint;mount.innerHTML='';modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';activeCleanup=g.start(mount,id);}
function closeGame(){if(activeCleanup)activeCleanup();activeCleanup=null;mount.innerHTML='';modal.classList.remove('show');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';}
$('#closeGame').onclick=closeGame;modal.querySelector('.modal-backdrop').onclick=closeGame;window.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('show'))closeGame()});
$('#randomBtn').onclick=()=>openGame(games[Math.floor(Math.random()*games.length)].id);$('#featuredBtn').onclick=()=>{category='Alle';$('#search').value='';document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.dataset.cat==='Alle'));window.scrollTo({top:360,behavior:'smooth'})};$('#search').oninput=render;document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{category=b.dataset.cat;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));render()});
$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'🔊':'🔇'};$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');$('#themeBtn').textContent=document.body.classList.contains('light')?'☀️':'☾'};render();
function canvasGame(mount,w=900,h=520){const c=document.createElement('canvas');c.width=w;c.height=h;mount.appendChild(c);const x=c.getContext('2d');return [c,x]}
function fitCanvas(c){const scale=Math.min((innerWidth*.86)/c.width,(innerHeight*.60)/c.height,1);c.style.width=Math.max(280,c.width*scale)+'px';c.style.height=Math.max(180,c.height*scale)+'px'}
function text(x,c,t,px,py,size=20,align='center'){c.save();c.font=`700 ${size}px system-ui`;c.textAlign=align;c.fillStyle=t;c.fillText(x,px,py);c.restore()}
function endScreen(ctx,w,h,score,best,msg='Runde vorbei'){ctx.fillStyle='#050916dd';ctx.fillRect(0,0,w,h);text(ctx,'#fff',msg,w/2,h/2-25,36);text(ctx,'#a9b5ce',`Score ${score} · Best ${best}`,w/2,h/2+18,17);text(ctx,'#7c5cff','Klick / Enter zum Neustart',w/2,h/2+58,14)}
function pointerPos(c,e){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}

function streetRush(mount,id){const [c,g]=canvasGame(mount,900,520);fitCanvas(c);const keys={};let lane=1,y=415,vy=0,slide=0,t=0,s=0,alive=true,last=performance.now(),obs=[],stars=[];const lanes=[270,450,630];function spawn(){obs.push({lane:Math.floor(Math.random()*3),z:0,type:Math.random()<.18?'slide':'jump'});if(Math.random()<.55)stars.push({lane:Math.floor(Math.random()*3),z:0})}function reset(){lane=1;y=415;vy=0;slide=0;t=0;s=0;obs=[];stars=[];alive=true;last=performance.now();requestAnimationFrame(loop)}function input(e){if(e.type==='keydown'){if(e.key==='ArrowLeft'||e.key==='a')lane=Math.max(0,lane-1);if(e.key==='ArrowRight'||e.key==='d')lane=Math.min(2,lane+1);if((e.key==='ArrowUp'||e.key==='w'||e.code==='Space')&&y>=415)vy=-17;if(e.key==='ArrowDown'||e.key==='s')slide=18;if(e.key==='Enter'&&!alive)reset()}else if(e.type==='pointerdown'){const p=pointerPos(c,e);if(!alive){reset();return}lane=p.x<c.width/3?0:p.x<c.width*2/3?1:2;if(p.y<c.height*.55&&y>=415)vy=-17;else if(p.y>c.height*.76)slide=18}}window.addEventListener('keydown',input);c.addEventListener('pointerdown',input);let spawnT=0;function loop(now){if(!alive)return;const dt=Math.min((now-last)/16,2);last=now;t+=dt;s+=dt*.12;spawnT-=dt;if(spawnT<=0){spawn();spawnT=Math.max(24,54-t*.01)}y+=vy*dt;vy+=.9*dt;if(y>415){y=415;vy=0}slide=Math.max(0,slide-dt);obs.forEach(o=>o.z+=.028*dt);stars.forEach(o=>o.z+=.034*dt);for(const o of obs){if(o.z>.88&&o.z<1.02&&o.lane===lane){const safe=(o.type==='jump'&&y<390)||(o.type==='slide'&&slide>0);if(!safe){alive=false;const best=Math.floor(s);setHS(id,best);highEl.textContent=`Highscore: ${getHS(id)}`}}}obs=obs.filter(o=>o.z<1.15);for(const a of stars)if(a.z>.87&&a.z<1.03&&a.lane===lane){s+=3;a.z=2}stars=stars.filter(a=>a.z<1.15&&a.z<1.5);g.fillStyle='#06101d';g.fillRect(0,0,c.width,c.height);const sky=g.createLinearGradient(0,0,0,520);sky.addColorStop(0,'#152b5b');sky.addColorStop(1,'#060a12');g.fillStyle=sky;g.fillRect(0,0,900,520);g.fillStyle='#1c2435';g.fillRect(0,430,900,90);for(let i=0;i<3;i++){g.strokeStyle='#57627a';g.lineWidth=3;g.beginPath();g.moveTo(lanes[i],430);g.lineTo(lanes[i],510);g.stroke()}for(let i=0;i<10;i++){let yy=435+i*13;g.fillStyle='#303b51';g.fillRect(0,yy,900,3)}obs.slice().sort((a,b)=>a.z-b.z).forEach(o=>{const p=Math.max(0,o.z),yy=420-p*320,ww=28+p*120;g.fillStyle=o.type==='jump'?'#ff5964':'#22d3a7';g.fillRect(lanes[o.lane]-ww/2,yy-ww*.6,ww,ww*.5)});stars.forEach(a=>{const p=a.z,yy=415-p*300;g.fillStyle='#ffe26a';g.beginPath();g.arc(lanes[a.lane],yy,8+p*7,0,Math.PI*2);g.fill()});g.fillStyle='#8b5cf6';const pw=slide?26:38,ph=slide?26:52;g.fillRect(lanes[lane]-pw/2,y-ph,pw,ph);text(g,'#fff',`Score ${Math.floor(s)}`,20,36,18,'left');if(!alive)endScreen(g,c.width,c.height,Math.floor(s),getHS(id),'Crash!');requestAnimationFrame(loop)}requestAnimationFrame(loop);return()=>{window.removeEventListener('keydown',input);c.remove();}}

function blastMaker(mount,id){const [c,g]=canvasGame(mount,660,650);fitCanvas(c);const N=8,cell=56,ox=106,oy=115;let board=Array.from({length:N},()=>Array(N).fill(0)),score=0,sel=null,game=true;const shapes=[[[1,1,1]],[[1,1],[1,1]],[[1,0],[1,1]],[[1,1,0],[0,1,1]],[[1,1,1],[0,1,0]],[[1,1,1,1]],[[1],[1],[1],[1]]];function draw(){g.clearRect(0,0,c.width,c.height);g.fillStyle='#091020';g.fillRect(0,0,c.width,c.height);text(g,'#fff','Blast Maker',330,48,30);text(g,'#94a3bd',`Score ${score}`,330,77,16);for(let r=0;r<N;r++)for(let q=0;q<N;q++){g.fillStyle=board[r][q]?'#7c5cff':'#151f34';g.fillRect(ox+q*cell,oy+r*cell,cell-4,cell-4)}if(sel){text(g,'#bac7df',`Block ${sel.length}×${sel[0].length}`,330,605,14)}else text(g,'#6f7c96','Wähle einen Block',330,605,14);shapes.forEach((s,i)=>{const x=40+i*88,y=560;g.fillStyle='#23304a';g.fillRect(x,y,72,60);g.fillStyle=i===0?'#24d2a3':'#9b8aff';s.forEach((row,r)=>row.forEach((v,q)=>v&&g.fillRect(x+12+q*12,y+12+r*12,10,10))) } if(!game)endScreen(g,c.width,c.height,score,getHS(id),'Keine Züge mehr');}
function place(r,q){if(!sel)return;for(let y=0;y<sel.length;y++)for(let x=0;x<sel[y].length;x++)if(sel[y][x]&&(!board[r+y]||board[r+y][q+x]))return;for(let y=0;y<sel.length;y++)for(let x=0;x<sel[y].length;x++)if(sel[y][x])board[r+y][q+x]=1;let cleared=0;for(let y=0;y<N;y++)if(board[y].every(Boolean)){board[y].fill(0);cleared++}for(let x=0;x<N;x++)if(board.every(row=>row[x])){for(let y=0;y<N;y++)board[y][x]=0;cleared++}score+=(sel.flat().filter(Boolean).length*2)+cleared*25;sel=null;game=shapes.some(s=>canAny(s));setHS(id,score);highEl.textContent=`Highscore: ${getHS(id)}`;draw()}function canAny(s){for(let r=0;r<N;r++)for(let q=0;q<N;q++){let ok=true;for(let y=0;y<s.length;y++)for(let x=0;x<s[y].length;x++)if(s[y][x]&&(!board[r+y]||board[r+y][q+x]))ok=false;if(ok)return true}return false}c.addEventListener('pointerdown',e=>{const p=pointerPos(c,e);if(p.y>=oy&&p.y<oy+N*cell&&sel){place(Math.floor((p.y-oy)/cell),Math.floor((p.x-ox)/cell));}else if(p.y>=550){const i=Math.floor((p.x-18)/88);if(shapes[i])sel=shapes[i];draw()}});draw();return()=>c.remove()}

function stackUp(mount,id){const [c,g]=canvasGame(mount,760,520);fitCanvas(c);let blocks=[{x:250,y:460,w:260}],moving={x:80,y:420,w:180},dir=1,score=0,alive=true,fall=0;function draw(){g.fillStyle='#08101f';g.fillRect(0,0,760,520);for(let i=0;i<blocks.length;i++){let b=blocks[i];g.fillStyle=i%2?'#24d2a3':'#8b7cff';g.fillRect(b.x,b.y,b.w,32)}if(alive){g.fillStyle='#ffcc66';g.fillRect(moving.x,moving.y,moving.w,32);text(g,'#fff',`Stack ${score}`,25,38,18,'left')}else endScreen(g,c.width,c.height,score,getHS(id),'Turm gefallen')}function drop(){if(!alive)return;const base=blocks[blocks.length-1],left=Math.max(base.x,moving.x),right=Math.min(base.x+base.w,moving.x+moving.w);if(right-left<25){alive=false;setHS(id,score);draw();return}blocks.push({x:left,y:420-blocks.length*38,w:right-left});score++;moving={x:60,y:420-blocks.length*38,w:Math.max(55,right-left)};dir=1;draw()}function loop(){if(alive){moving.x+=dir*(3.2+score*.06);if(moving.x<20||moving.x+moving.w>740)dir*=-1;draw();requestAnimationFrame(loop)}}window.addEventListener('keydown',e=>{if(e.code==='Space'){if(!alive){blocks=[{x:250,y:460,w:260}];moving={x:80,y:420,w:180};score=0;alive=true;loop()}else drop()}});c.addEventListener('pointerdown',()=>alive?drop(): (blocks=[{x:250,y:460,w:260}],moving={x:80,y:420,w:180},score=0,alive=true,loop()));loop();return()=>c.remove()}

function snakeArena(mount,id){const [c,g]=canvasGame(mount,600,600);fitCanvas(c);const n=20,size=24;let snake=[{x:10,y:10}],dir={x:1,y:0},next={x:1,y:0},food={x:15,y:15},score=0,alive=true,last=0;function newFood(){food={x:Math.floor(Math.random()*n),y:Math.floor(Math.random()*n)}}function step(){if(!alive)return;dir=next;const h={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(h.x<0||h.y<0||h.x>=n||h.y>=n||snake.some((p,i)=>i>0&&p.x===h.x&&p.y===h.y)){alive=false;setHS(id,score);return}snake.unshift(h);if(h.x===food.x&&h.y===food.y){score+=10;newFood()}else snake.pop()}function draw(){g.fillStyle='#08101c';g.fillRect(0,0,600,600);g.strokeStyle='#14233b';for(let i=0;i<=n;i++){g.beginPath();g.moveTo(i*size,0);g.lineTo(i*size,600);g.stroke();g.beginPath();g.moveTo(0,i*size);g.lineTo(600,i*size);g.stroke()}g.fillStyle='#ffcb66';g.fillRect(food.x*size+3,food.y*size+3,size-6,size-6);snake.forEach((p,i)=>{g.fillStyle=i?'#5ce6bd':'#a996ff';g.fillRect(p.x*size+2,p.y*size+2,size-4,size-4)});text(g,'#fff',`Score ${score}`,15,28,16,'left');if(!alive)endScreen(g,600,600,score,getHS(id),'Game Over')}function loop(t){if(t-last>105){step();last=t}draw();requestAnimationFrame(loop)}function key(e){const k=e.key.toLowerCase();if(k==='arrowup'||k==='w')next={x:0,y:-1};if(k==='arrowdown'||k==='s')next={x:0,y:1};if(k==='arrowleft'||k==='a')next={x:-1,y:0};if(k==='arrowright'||k==='d')next={x:1,y:0};if(!alive&&k==='enter'){snake=[{x:10,y:10}];next=dir={x:1,y:0};score=0;alive=true}}window.addEventListener('keydown',key);let px=0,py=0;c.addEventListener('pointerdown',e=>{const p=pointerPos(c,e);px=p.x;py=p.y});c.addEventListener('pointerup',e=>{const p=pointerPos(c,e),dx=p.x-px,dy=p.y-py;if(Math.abs(dx)>Math.abs(dy))next=dx>0?{x:1,y:0}:{x:-1,y:0};else next=dy>0?{x:0,y:1}:{x:0,y:-1}});requestAnimationFrame(loop);return()=>{window.removeEventListener('keydown',key);c.remove()}}

function skyFlap(mount,id){const [c,g]=canvasGame(mount,800,500);fitCanvas(c);let y=250,vy=0,pipes=[],score=0,alive=true,frame=0;function flap(){if(!alive){y=250;vy=0;pipes=[];score=0;alive=true;return}vy=-8}function loop(){frame++;if(alive){vy+=.42;y+=vy;if(frame%95===0){const gap=145,top=70+Math.random()*220;pipes.push({x:820,top,gap})}pipes.forEach(p=>p.x-=4);pipes=pipes.filter(p=>p.x>-80);pipes.forEach(p=>{if(!p.hit&&p.x<120){p.hit=true;score++}if(120+18>p.x&&120-18<p.x+60&&(y< p.top||y>p.top+p.gap))alive=false});if(y<15||y>485)alive=false;if(!alive){setHS(id,score);}}g.fillStyle='#0b1930';g.fillRect(0,0,800,500);g.fillStyle='#17385a';g.fillRect(0,360,800,140);pipes.forEach(p=>{g.fillStyle='#38d39f';g.fillRect(p.x,0,60,p.top);g.fillRect(p.x,p.top+p.gap,60,500)});g.fillStyle='#ffe38a';g.beginPath();g.arc(120,y,18,0,Math.PI*2);g.fill();text(g,'#fff',String(score),400,45,28);if(!alive)endScreen(g,800,500,score,getHS(id),'Platsch!');else requestAnimationFrame(loop)}c.addEventListener('pointerdown',flap);window.addEventListener('keydown',e=>{if(e.code==='Space'||e.key==='ArrowUp')flap()});requestAnimationFrame(loop);return()=>{c.remove();window.removeEventListener('keydown',flap)}}

function brickBreaker(mount,id){const [c,g]=canvasGame(mount,820,540);fitCanvas(c);let px=350,ball={x:410,y:450,vx:4,vy:-4},bricks=[],score=0,life=3,alive=true;for(let r=0;r<5;r++)for(let q=0;q<10;q++)bricks.push({x:20+q*80,y:55+r*28,w:72,h:20,on:1});function resetBall(){ball={x:410,y:450,vx:(Math.random()>.5?4:-4),vy:-4}}function loop(){if(!alive)return;ball.x+=ball.vx;ball.y+=ball.vy;if(ball.x<8||ball.x>812)ball.vx*=-1;if(ball.y<8)ball.vy*=-1;if(ball.y>510){life--;if(life<=0){alive=false;setHS(id,score)}else resetBall()}if(ball.y+8>465&&ball.y<490&&ball.x>px&&ball.x<px+120){ball.vy=-Math.abs(ball.vy);ball.vx+=(ball.x-(px+60))*.035}for(const b of bricks)if(b.on&&ball.x>b.x&&ball.x<b.x+b.w&&ball.y> b.y&&ball.y<b.y+b.h){b.on=0;score+=10;ball.vy*=-1;break}if(bricks.every(b=>!b.on)){score+=100;bricks.forEach(b=>b.on=1);ball.vy*=1.08}g.fillStyle='#070d19';g.fillRect(0,0,820,540);bricks.forEach((b,i)=>{if(b.on){g.fillStyle=i%2?'#7c5cff':'#24d2a3';g.fillRect(b.x,b.y,b.w,b.h)}});g.fillStyle='#fff';g.fillRect(px,470,120,14);g.beginPath();g.arc(ball.x,ball.y,8,0,Math.PI*2);g.fill();text(g,'#fff',`Score ${score}  •  Leben ${life}`,15,32,16,'left');if(!alive)endScreen(g,c.width,c.height,score,getHS(id));else requestAnimationFrame(loop)}function key(e){if(e.key==='ArrowLeft'||e.key==='a')px=Math.max(8,px-35);if(e.key==='ArrowRight'||e.key==='d')px=Math.min(692,px+35);if(!alive&&e.key==='Enter')location.reload()}c.addEventListener('pointermove',e=>{px=pointerPos(c,e).x-60;px=Math.max(8,Math.min(692,px))});window.addEventListener('keydown',key);requestAnimationFrame(loop);return()=>{c.remove();window.removeEventListener('keydown',key)}}

function astroDrift(mount,id){const [c,g]=canvasGame(mount,820,520);fitCanvas(c);let ship={x:410,y:260,a:-Math.PI/2,vx:0,vy:0},shots=[],rocks=[],score=0,alive=true,keys={};for(let i=0;i<9;i++)rocks.push({x:Math.random()*820,y:Math.random()*520,r:18+Math.random()*27,vx:(Math.random()-.5)*2.6,vy:(Math.random()-.5)*2.6});function key(e){keys[e.key.toLowerCase()]=e.type==='keydown';if(!alive&&e.key==='Enter')return start()}function start(){ship={x:410,y:260,a:-Math.PI/2,vx:0,vy:0};shots=[];rocks=[];score=0;alive=true;for(let i=0;i<9;i++)rocks.push({x:Math.random()*820,y:Math.random()*520,r:18+Math.random()*27,vx:(Math.random()-.5)*2.6,vy:(Math.random()-.5)*2.6});loop()}function fire(){if(alive)shots.push({x:ship.x+Math.cos(ship.a)*18,y:ship.y+Math.sin(ship.a)*18,vx:Math.cos(ship.a)*8,vy:Math.sin(ship.a)*8,life:80})}let firing=false;function loop(){if(!alive)return;if(keys.arrowleft||keys.a)ship.a-=.065;if(keys.arrowright||keys.d)ship.a+=.065;if(keys.arrowup||keys.w){ship.vx+=Math.cos(ship.a)*.11;ship.vy+=Math.sin(ship.a)*.11}ship.x=(ship.x+ship.vx+820)%820;ship.y=(ship.y+ship.vy+520)%520;ship.vx*=.992;ship.vy*=.992;if(keys[' ']){if(!firing)fire();firing=true}else firing=false;shots.forEach(s=>{s.x+=s.vx;s.y+=s.vy;s.life--});shots=shots.filter(s=>s.life>0);rocks.forEach(r=>{r.x=(r.x+r.vx+820)%820;r.y=(r.y+r.vy+520)%520});for(const s of shots)for(const r of rocks)if(r.r>0&&Math.hypot(s.x-r.x,s.y-r.y)<r.r){r.r=0;score+=10;s.life=0}rocks=rocks.filter(r=>r.r>0);if(rocks.length<5)rocks.push({x:Math.random()*820,y:Math.random()*520,r:20+Math.random()*25,vx:(Math.random()-.5)*2.5,vy:(Math.random()-.5)*2.5});if(rocks.some(r=>Math.hypot(ship.x-r.x,ship.y-r.y)<r.r+14)){alive=false;setHS(id,score)}g.fillStyle='#030711';g.fillRect(0,0,820,520);for(let i=0;i<100;i++){g.fillStyle='#ffffff15';g.fillRect((i*83)%820,(i*47)%520,2,2)}rocks.forEach(r=>{g.strokeStyle='#8e9bb3';g.lineWidth=3;g.beginPath();g.arc(r.x,r.y,r.r,0,7);g.stroke()});shots.forEach(s=>{g.fillStyle='#ffe66b';g.fillRect(s.x-2,s.y-2,4,4)});g.save();g.translate(ship.x,ship.y);g.rotate(ship.a);g.fillStyle='#a996ff';g.beginPath();g.moveTo(18,0);g.lineTo(-13,-10);g.lineTo(-8,0);g.lineTo(-13,10);g.closePath();g.fill();g.restore();text(g,'#fff',`Score ${score}`,15,30,16,'left');if(!alive)endScreen(g,820,520,score,getHS(id),'Schiff zerstört');requestAnimationFrame(loop)}c.addEventListener('pointerdown',fire);window.addEventListener('keydown',key);window.addEventListener('keyup',key);requestAnimationFrame(loop);return()=>{c.remove();window.removeEventListener('keydown',key);window.removeEventListener('keyup',key)}}

function memoryGrid(mount,id){const [c,g]=canvasGame(mount,680,520);fitCanvas(c);const vals=['🍋','🍒','🍇','🥝','🍉','🥥','🍓','🍊'];let cards=[...vals,...vals].sort(()=>Math.random()-.5).map((v,i)=>({v,i,open:false,done:false})),first=null,lock=false,moves=0;function draw(){g.fillStyle='#08101d';g.fillRect(0,0,680,520);text(g,'#fff',`Memory · ${moves} Züge`,340,35,22);cards.forEach((cd,i)=>{const q=i%4,r=Math.floor(i/4),x=95+q*125,y=70+r*105;g.fillStyle=cd.open||cd.done?'#252e46':'#111a2e';g.fillRect(x,y,98,78);if(cd.open||cd.done)text(g,'#fff',cd.v,x+49,y+50,32);else text(g,'#586681','?',x+49,y+50,26)});if(cards.every(a=>a.done)){setHS(id,Math.max(1,1000-moves*12));endScreen(g,c.width,c.height,Math.max(1,1000-moves*12),getHS(id),'Alles gefunden!')}}c.addEventListener('pointerdown',e=>{if(lock)return;const p=pointerPos(c,e);let idx=-1;cards.forEach((cd,i)=>{const q=i%4,r=Math.floor(i/4),x=95+q*125,y=70+r*105;if(p.x>x&&p.x<x+98&&p.y>y&&p.y<y+78)idx=i});if(idx<0||cards[idx].done||cards[idx].open)return;cards[idx].open=true;moves++;if(first===null)first=idx;else{const second=idx;lock=true;setTimeout(()=>{if(cards[first].v===cards[second].v){cards[first].done=cards[second].done=true}else{cards[first].open=cards[second].open=false}first=null;lock=false;draw()},520)}draw()});draw();return()=>c.remove()}

function neonTiles(mount,id){const [c,g]=canvasGame(mount,520,520);fitCanvas(c);let b=[[2,0,0,4],[0,0,2,0],[0,0,0,0],[0,0,0,0]],score=0,over=false;function spawn(){let z=[];for(let y=0;y<4;y++)for(let x=0;x<4;x++)if(!b[y][x])z.push([y,x]);if(z.length){const [y,x]=z[Math.floor(Math.random()*z.length)];b[y][x]=Math.random()<.9?2:4}}function slide(a){a=a.filter(Boolean);for(let i=0;i<a.length-1;i++)if(a[i]===a[i+1]){a[i]*=2;score+=a[i];a[i+1]=0}return a.filter(Boolean).concat(Array(4-a.filter(Boolean).length).fill(0))}function move(dx,dy){let before=JSON.stringify(b);if(dx!==0){for(let y=0;y<4;y++){let a=b[y].slice();if(dx>0)a.reverse();a=slide(a);if(dx>0)a.reverse();b[y]=a}}else{for(let x=0;x<4;x++){let a=[b[0][x],b[1][x],b[2][x],b[3][x]];if(dy>0)a.reverse();a=slide(a);if(dy>0)a.reverse();for(let y=0;y<4;y++)b[y][x]=a[y]}}if(JSON.stringify(b)!==before){spawn();over=!canMove()}draw()}function canMove(){for(let y=0;y<4;y++)for(let x=0;x<4;x++)if(!b[y][x]||(b[y][x]===b[y+1]?.[x])||(b[y][x]===b[y]?.[x+1]))return true;return false}function draw(){g.fillStyle='#09101e';g.fillRect(0,0,520,520);text(g,'#fff',`Neon Tiles · ${score}`,260,35,21);for(let y=0;y<4;y++)for(let x=0;x<4;x++){g.fillStyle=b[y][x]?'#6e60d9':'#17233a';g.fillRect(40+x*112,65+y*112,104,104);if(b[y][x])text(g,'#fff',String(b[y][x]),92+x*112,130+y*112,26)}if(over)endScreen(g,c.width,c.height,score,getHS(id),'Keine Züge mehr')}function key(e){const k=e.key.toLowerCase();if(k==='arrowleft'||k==='a')move(-1,0);if(k==='arrowright'||k==='d')move(1,0);if(k==='arrowup'||k==='w')move(0,-1);if(k==='arrowdown'||k==='s')move(0,1)}window.addEventListener('keydown',key);draw();return()=>{window.removeEventListener('keydown',key);c.remove()}}

function aimDash(mount,id){const [c,g]=canvasGame(mount,800,520);fitCanvas(c);let target={x:400,y:260,r:28},score=0,time=30,last=performance.now(),best=0,done=false;function place(){target={x:50+Math.random()*700,y:80+Math.random()*360,r:18+Math.random()*22}}function draw(t){g.fillStyle='#070d19';g.fillRect(0,0,800,520);g.fillStyle='#24d2a3';g.beginPath();g.arc(target.x,target.y,target.r,0,7);g.fill();g.fillStyle='#07101c';g.beginPath();g.arc(target.x,target.y,target.r*.4,0,7);g.fill();text(g,'#fff',`Treffer ${score}`,20,32,18,'left');text(g,'#fff',`${Math.max(0,time).toFixed(1)}s`,780,32,18,'right');if(time<=0)done=true;if(done){best=score;setHS(id,best);endScreen(g,800,520,score,getHS(id),'Zeit vorbei')}else requestAnimationFrame(loop)}function loop(now){time-=((now-last)/1000);last=now;draw(now)}c.addEventListener('pointerdown',e=>{if(done){score=0;time=30;done=false;last=performance.now();place();requestAnimationFrame(loop);return}const p=pointerPos(c,e);if(Math.hypot(p.x-target.x,p.y-target.y)<target.r){score++;place();if(score>getHS(id))setHS(id,score)}});place();requestAnimationFrame(loop);return()=>c.remove()}

function goalRush(mount,id){const [c,g]=canvasGame(mount,800,520);fitCanvas(c);let ball={x:130,y:420},goal={x:650,y:220,r:55},shots=0,goals=0,drag=null,anim=null;function draw(){g.fillStyle='#071318';g.fillRect(0,0,800,520);g.fillStyle='#185a42';g.fillRect(0,320,800,200);g.strokeStyle='#e9f7ee';g.lineWidth=4;g.strokeRect(540,120,180,200);g.strokeStyle='#90a8b8';g.beginPath();g.moveTo(110,420);g.lineTo(540,220);g.stroke();g.fillStyle='#1d8d5e';g.beginPath();g.arc(ball.x,ball.y,16,0,7);g.fill();g.strokeStyle='#f6f7fb';g.lineWidth=7;g.beginPath();g.arc(goal.x,goal.y,goal.r,0,7);g.stroke();text(g,'#fff',`Tore ${goals} · Schüsse ${shots}`,18,32,18,'left');if(anim){ball.x+=anim.vx;ball.y+=anim.vy;anim.vx*=.985;anim.vy*=.985;if(Math.hypot(ball.x-goal.x,ball.y-goal.y)<goal.r){goals++;setHS(id,goals);highEl.textContent=`Highscore: ${getHS(id)}`;anim=null;ball={x:130,y:420}}else if(ball.x>810||ball.y<0||ball.y>540||Math.hypot(anim.vx,anim.vy)<.25){anim=null;ball={x:130,y:420}}}requestAnimationFrame(draw)}c.addEventListener('pointerdown',e=>{const p=pointerPos(c,e);if(!anim)drag={x:p.x,y:p.y}});c.addEventListener('pointerup',e=>{if(!drag||anim)return;const p=pointerPos(c,e);const dx=drag.x-p.x,dy=drag.y-p.y;shots++;anim={vx:dx*.08,vy:dy*.08};drag=null});requestAnimationFrame(draw);return()=>c.remove()}

function fruitSlice(mount,id){const [c,g]=canvasGame(mount,800,520);fitCanvas(c);let items=[],score=0,miss=0,alive=true,t=0,last=performance.now(),trail=[];function spawn(){items.push({x:40+Math.random()*720,y:530,vx:(Math.random()-.5)*4,vy:-10-Math.random()*6,r:18+Math.random()*13,bomb:Math.random()<.15})}function loop(now){const dt=Math.min((now-last)/16,2);last=now;t+=dt;if(alive&&Math.random()<.045*dt)spawn();items.forEach(a=>{a.x+=a.vx*dt;a.y+=a.vy*dt;a.vy+=.25*dt});items=items.filter(a=>{if(a.y>550){if(!a.bomb)miss++;return false}return true});if(miss>12)alive=false;if(!alive){setHS(id,score)}g.fillStyle='#07111c';g.fillRect(0,0,800,520);items.forEach(a=>{g.fillStyle=a.bomb?'#ff5364':(['#ff9f43','#55d6a6','#a58cff'][Math.floor(a.x)%3]);g.beginPath();g.arc(a.x,a.y,a.r,0,7);g.fill();text(g,'#07111c',a.bomb?'!':'•',a.x,a.y+7,18)});g.strokeStyle='#fff8';g.lineWidth=5;g.beginPath();trail.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.stroke();trail=trail.slice(-12);text(g,'#fff',`Score ${score} · Fehlt ${miss}/12`,15,32,17,'left');if(!alive)endScreen(g,800,520,score,getHS(id),'Zu viele verpasst');else requestAnimationFrame(loop)}function cut(p){trail.push(p);items.forEach(a=>{if(Math.hypot(p.x-a.x,p.y-a.y)<a.r+12){if(a.bomb)alive=false;else{score+=5;a.y=700}}})}c.addEventListener('pointermove',e=>cut(pointerPos(c,e)));requestAnimationFrame(loop);return()=>c.remove()}

function laserDodge(mount,id){const [c,g]=canvasGame(mount,820,520);fitCanvas(c);let px=410,lasers=[],score=0,alive=true,t=0,last=performance.now();function loop(now){const dt=Math.min((now-last)/16,2);last=now;t+=dt;if(alive){if(Math.random()<.03*dt)lasers.push({y:70+Math.random()*390,x:Math.random()*820,w:60+Math.random()*150,spd:2+Math.min(3,score*.01)});lasers.forEach(l=>l.x+=l.spd*dt);lasers=lasers.filter(l=>l.x<850);score+=dt*.1;if(lasers.some(l=>px>l.x-10&&px<l.x+l.w+10)){alive=false;setHS(id,Math.floor(score))}}g.fillStyle='#050912';g.fillRect(0,0,820,520);g.fillStyle='#a997ff';g.fillRect(px-13,455,26,26);lasers.forEach(l=>{g.fillStyle='#ff5168';g.shadowBlur=16;g.shadowColor='#ff5168';g.fillRect(l.x,l.y,l.w,8);g.shadowBlur=0});text(g,'#fff',`Score ${Math.floor(score)}`,18,31,18,'left');if(!alive)endScreen(g,820,520,Math.floor(score),getHS(id),'Getroffen');else requestAnimationFrame(loop)}function key(e){if(e.key==='ArrowLeft'||e.key==='a')px=Math.max(15,px-28);if(e.key==='ArrowRight'||e.key==='d')px=Math.min(805,px+28);if(!alive&&e.key==='Enter')location.reload()}window.addEventListener('keydown',key);c.addEventListener('pointerdown',e=>px=pointerPos(c,e).x);c.addEventListener('pointermove',e=>px=pointerPos(c,e).x);requestAnimationFrame(loop);return()=>{window.removeEventListener('keydown',key);c.remove()}}

function reactionRush(mount,id){const [c,g]=canvasGame(mount,720,420);fitCanvas(c);let state='wait',started=performance.now(),ready=0,best=Infinity;function draw(){g.fillStyle=state==='go'?'#24a96f':state==='wait'?'#b42d46':'#15213a';g.fillRect(0,0,720,420);text(g,'#fff',state==='go'?'KLICK!':state==='wait'?'Warte auf Grün…':'Nochmal?',360,185,42);if(state==='result')text(g,'#d2dae8',`${best} ms · Klicke zum Neustart`,360,250,18);else text(g,'#d2dae8','Klicke überall',360,250,16)}function begin(){state='wait';draw();ready=setTimeout(()=>{state='go';started=performance.now();draw()},900+Math.random()*2500)}function click(){if(state==='wait'){clearTimeout(ready);state='result';draw()}else if(state==='go'){best=Math.round(performance.now()-started);setHS(id,100000-best);highEl.textContent=`Highscore: ${getHS(id)}`;state='result';draw()}else begin()}c.addEventListener('pointerdown',click);begin();return()=>{clearTimeout(ready);c.remove()}}

function init(){render()}init();