(()=>{
'use strict';
const $=id=>document.getElementById(id);const stage=$('stage'),title=$('title'),cat=$('cat'),scoreEl=$('score'),bestEl=$('best'),hint=$('hint'),restart=$('restart'),pause=$('pause');
const W=1200,H=700,c=document.createElement('canvas');c.width=W;c.height=H;c.style.touchAction='none';stage.innerHTML='';stage.appendChild(c);const g=c.getContext('2d');
const key='rg-hs-street';let best=Number(localStorage.getItem(key)||0),score=0,lane=1,targetLane=1,jump=0,duck=0,dead=false,paused=false,last=performance.now(),speed=0.34,dist=0,spawnT=0,coinT=0,obstacles=[],coins=[],particles=[],shake=0,raf;
function fit(){const s=Math.min(innerWidth/W,innerHeight/H);c.style.width=(W*s)+'px';c.style.height=(H*s)+'px'}fit();addEventListener('resize',fit);
title.textContent='Street Rush';cat.textContent='ACTION';bestEl.textContent='Best '+best;hint.textContent='← → Spur · ↑ / Space springen · ↓ ducken · Wischen auf Mobil';
function hs(v){if(v>best){best=v;localStorage.setItem(key,best);bestEl.textContent='Best '+best}}
function reset(){score=0;lane=1;targetLane=1;jump=0;duck=0;dead=false;paused=false;speed=.34;dist=0;spawnT=0;coinT=0;obstacles=[];coins=[];particles=[];shake=0;last=performance.now();pause.textContent='Ⅱ Pause';raf=requestAnimationFrame(loop)}
function die(){if(dead)return;dead=true;hs(Math.floor(score));for(let i=0;i<36;i++)particles.push({x:W/2,y:H*.68,vx:(Math.random()-.5)*10,vy:(Math.random()-.7)*10,l:40+Math.random()*35,s:2+Math.random()*5})}
function input(e){if(e.key==='Escape'){paused=!paused;pause.textContent=paused?'▶ Weiter':'Ⅱ Pause';return}const k=e.key?.toLowerCase();if((e.key==='ArrowLeft'||k==='a')&&!dead&&!paused)targetLane=Math.max(0,targetLane-1);if((e.key==='ArrowRight'||k==='d')&&!dead&&!paused)targetLane=Math.min(2,targetLane+1);if((e.key==='ArrowUp'||e.code==='Space'||k==='w')){if(dead){reset();return}if(!paused&&jump<=0.01)jump=1}if(e.key==='ArrowDown'||k==='s')duck=.34;if(e.key==='Enter'&&dead)reset()}
addEventListener('keydown',input);restart.onclick=reset;pause.onclick=()=>{paused=!paused;pause.textContent=paused?'▶ Weiter':'Ⅱ Pause'};
let sx=0,sy=0;c.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY;if(dead){reset();return}});c.addEventListener('pointerup',e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)){targetLane=Math.max(0,Math.min(2,targetLane+(dx>0?1:-1)));return}if(Math.abs(dy)>45){if(dy<0&&jump<=.01)jump=1;else if(dy>0)duck=.34;return}const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width;if(x<.34)targetLane=0;else if(x>.66)targetLane=2;else if(jump<=.01)jump=1});
function roadX(l,z){const horizon=255,roadBottom=1120,t=Math.pow(z,.88);return W/2+(l-1)*([0,185,370][l])*t}
function sxLane(l,z){const horizon=255,bottom=1120,spread=190*tScale(z);return W/2+(l-1)*spread}
function tScale(z){return Math.pow(z,.88)}
function project(l,z){const t=tScale(z);return {x:W/2+(l-1)*360*t,y:255+445*t,scale:.12+1.05*t}}
function spawn(){const type=Math.random()<.2?'barrier':Math.random()<.5?'train':'jump';const l=Math.floor(Math.random()*3);obstacles.push({l,z:0,type,checked:false})}
function spawnCoinLine(){const l=Math.floor(Math.random()*3);for(let i=0;i<5;i++)coins.push({l,z:-i*.11,got:false})}
function particle(x,y){for(let i=0;i<8;i++)particles.push({x,y,vx:(Math.random()-.5)*3,vy:-Math.random()*3,l:20+Math.random()*15,s:1+Math.random()*3})}
function drawSky(){const sky=g.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#5fa8ff');sky.addColorStop(.55,'#cbe8ff');sky.addColorStop(.56,'#a8d08a');sky.addColorStop(1,'#41622d');g.fillStyle=sky;g.fillRect(0,0,W,H);g.fillStyle='rgba(255,255,255,.65)';for(let i=0;i<6;i++){const x=((i*250-dist*45)%1450)-120,y=85+(i%3)*34;g.beginPath();g.ellipse(x,y,70,18,0,0,Math.PI*2);g.fill()}for(let i=0;i<18;i++){const x=((i*97-dist*10)%1500)-140;const y=165+(i%6)*13;g.fillStyle=i%2?'#6ea25a':'#587e49';g.fillRect(x,y,8,65);g.beginPath();g.arc(x+4,y,24,0,Math.PI*2);g.fill()}}
function drawRoad(){g.fillStyle='#545762';g.beginPath();g.moveTo(W/2-62,255);g.lineTo(W/2+62,255);g.lineTo(W/2+520,700);g.lineTo(W/2-520,700);g.closePath();g.fill();g.fillStyle='#252831';g.beginPath();g.moveTo(W/2-34,255);g.lineTo(W/2+34,255);g.lineTo(W/2+290,700);g.lineTo(W/2-290,700);g.closePath();g.fill();for(const l of [0,2]){for(let i=0;i<18;i++){const z=(i/18+(dist%1)/4)%1;const p=project(l,z);g.fillStyle='rgba(255,255,255,.68)';g.fillRect(p.x-5*p.scale,p.y,10*p.scale,4*p.scale)}}for(let i=0;i<28;i++){const z=(i/28+(dist%1)/5)%1;const y=255+445*tScale(z);const sw=3+20*tScale(z);g.fillStyle='#fff';g.fillRect(W/2-sw/2,y,sw,3+6*tScale(z))}}
function drawTrain(p){const w=110*p.scale,h=150*p.scale;g.save();g.translate(p.x,p.y-h);g.fillStyle='#294d6a';g.fillRect(-w/2,0,w,h);g.fillStyle='#a9d7ee';for(let i=-1;i<=1;i++)g.fillRect(-w*.32+i*w*.32,w*.12,w*.22,w*.18);g.fillStyle='#de3e52';g.fillRect(-w*.44,h*.67,w*.88,h*.18);g.restore()}
function drawBarrier(p){const w=100*p.scale,h=62*p.scale;g.save();g.translate(p.x,p.y-h*.2);g.fillStyle='#e64d49';g.fillRect(-w/2,-h/2,w,h);g.fillStyle='#ffe07a';for(let i=-2;i<3;i++)g.fillRect(-w/2+i*w*.24,-h*.3,w*.11,h*.6);g.restore()}
function drawCoin(p){g.save();g.translate(p.x,p.y-25*p.scale);g.scale(p.scale,p.scale);g.fillStyle='#ffd866';g.beginPath();g.arc(0,0,18,0,Math.PI*2);g.fill();g.strokeStyle='#fff2ad';g.lineWidth=3;g.stroke();g.fillStyle='#b47711';g.font='900 19px system-ui';g.textAlign='center';g.fillText('R',0,7);g.restore()}
function drawCharacter(){lane+=(targetLane-lane)*.18;const groundY=620;const jumpY=jump>0?Math.sin((1-jump)*Math.PI)*230:0;const ducking=duck>0;const x=W/2+(lane-1)*180;const y=groundY-jumpY;const run=Math.sin(dist*28);g.save();g.translate(x,y);if(ducking)g.scale(1,.62);g.shadowColor='rgba(0,0,0,.3)';g.shadowBlur=18;g.fillStyle='#20283b';g.beginPath();g.arc(0,-96,30,0,Math.PI*2);g.fill();g.fillStyle='#7e64ff';g.fillRect(-24,-66,48,78);g.strokeStyle='#20283b';g.lineWidth=16;g.lineCap='round';g.beginPath();g.moveTo(-18,-52);g.lineTo(-55,-25+run*10);g.moveTo(18,-52);g.lineTo(55,-25-run*10);g.stroke();g.beginPath();g.moveTo(-12,10);g.lineTo(-30,65+run*14);g.moveTo(12,10);g.lineTo(30,65-run*14);g.stroke();g.fillStyle='#f5c8a8';g.fillRect(-13,-115,8,7);g.fillRect(5,-115,8,7);g.restore()}
function loop(now){const dt=Math.min(2,(now-last)/16);last=now;if(!paused&&!dead){dist+=speed*dt;score+=.085*speed*dt;speed=Math.min(.7,.34+score/900);spawnT-=dt;coinT-=dt;if(spawnT<=0){spawn();spawnT=Math.max(25,58-score/25)}if(coinT<=0){spawnCoinLine();coinT=110}if(jump>0)jump=Math.max(0,jump-.035*dt);if(duck>0)duck=Math.max(0,duck-.035*dt);lane+=(targetLane-lane)*.2;for(const o of obstacles){o.z+=speed*dt;if(!o.checked&&o.z>.84&&o.z<.98&&Math.abs(o.l-(lane>1.6?2:lane<.4?0:1))<.3){o.checked=true;const safe=(o.type==='jump'&&jump>.15);if(!safe)die()}}for(const q of coins){q.z+=speed*dt;if(!q.got&&q.z>.82&&q.z<1.02&&Math.round(lane)===q.l){q.got=true;score+=3;particle(W/2+(q.l-1)*160,550)}}obstacles=obstacles.filter(o=>o.z<1.15);coins=coins.filter(o=>o.z<1.2&&(!o.got||o.z<.86));}
 drawSky();drawRoad();const sorted=[...obstacles].sort((a,b)=>a.z-b.z);sorted.forEach(o=>{const p=project(o.l,o.z);if(o.type==='train')drawTrain(p);else drawBarrier(p)});coins.filter(q=>!q.got).sort((a,b)=>a.z-b.z).forEach(q=>drawCoin(project(q.l,q.z)));drawCharacter();for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=.2*dt;p.l-=dt;g.globalAlpha=Math.max(0,p.l/35);g.fillStyle='#ffe076';g.fillRect(p.x,p.y,p.s,p.s)}g.globalAlpha=1;hud(g,score);if(dead)gameOver();raf=requestAnimationFrame(loop)}
function hud(g,s){g.fillStyle='rgba(5,10,20,.55)';g.fillRect(18,18,250,72);g.fillStyle='#fff';g.font='800 24px system-ui';g.fillText('Score '+Math.floor(s),34,49);g.font='700 15px system-ui';g.fillStyle='#dbe7f7';g.fillText('Best '+best,34,74)}
function gameOver(){g.fillStyle='rgba(3,6,14,.72)';g.fillRect(0,0,W,H);g.textAlign='center';g.fillStyle='#fff';g.font='900 58px system-ui';g.fillText('LAUF VORBEI!',W/2,270);g.font='800 28px system-ui';g.fillText('Score '+Math.floor(score),W/2,320);g.fillStyle='#c9d4e8';g.font='600 18px system-ui';g.fillText('Klick, Enter oder ↻ für einen neuen Lauf',W/2,360);g.textAlign='left'}
reset();
})();